INCLUDE_CJSON=1
INCLUDE_SHMVAR=1
include ../common/config.mk

TARGET = storyTeller
LDFLAGS := $(LDFLAGS) -lpthread -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer -lSDL2_gfx

include ../common/commands.mk
include ../common/recipes.mk
