# ALSA R36S — dmix + plug (SDL_mixer 44100, moins d'underruns qu'un hw direct)
pcm.!default {
	type plug
	slave.pcm "dmixer"
}

pcm.dmixer {
	type dmix
	ipc_key 2244
	slave {
		pcm "hw:0,0"
		period_size 1024
		buffer_size 8192
		rate 44100
		format S16_LE
		channels 2
	}
}

ctl.!default {
	type hw
	card 0
}
